version: '3'
services:
  api:
    container_name: order-manager-api
    image: order-manager-api
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: postgres-db-order-manager-api
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order-manager-db
    ports:
      - "5434:5432"

